# Generated by Django 5.1.2 on 2025-02-01 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20250201_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'لیست سفارشات'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='manufacturer',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='product_type',
            field=models.CharField(default='میلگرد', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='requester_name',
            field=models.CharField(default='ناشناخته', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(default='نامشخص', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='unloading_place',
            field=models.CharField(default='ناشناخته', max_length=100),
        ),
    ]
